### ISSUE TITLE
url embedded resources

### ISSUE THREAD

**Issue by Simonl9l** [milkshakesoftware/PreMailer.Net#235]
Hi,

Per PreMailer.Net ver 2.2.0

I have a CSS file that has base64 encoded images (as generated via webpack). 
```css
.pt-logo {
  background-image: url(data:image/png;base64,iVBORw0KG...);
  background-repeat: no-repeat; }
```
where `iVBORw0KG...` is the start of the base64 encoded image (truncated for clarity/brevity), and similarly encoded svg's:
```css
my-icon {
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' width='8' height='8' viewBox='0 0 8 8'%3e%3cpath d='M5.25 0l-4 4 4 4 1.5-1.5L4.25 4l2.5-2.5L5.25 0z'/%3e%3c/svg%3e"); }
```
we have similar for fonts and other artifacts.

With the style linked, and given the HTML:
```HTML
    <span class="pt-logo"></span>
```
It seem that the `PreMailer.MoveCssInline` call reduces this to:
```HTML
    <span class="pt-logo" style="background-image: url(data:image/png;background-repeat: no-repeat;></span>
```
The `base64` image data (and similarly `svg+xml` data for that matter) is eliminated e.g. `base64,iVBORw0KG...`

Am I doing something wrong or does PreMailer not currently handle this scenario? If the latter is this fixable?

I have attempted to `ignoreElements: "pt-logo" ` to no avail. Any recomendations?
