### ISSUE TITLE
Two same CSS properties on same dom element does not work

### ISSUE THREAD

**Issue by seawerst** [milkshakesoftware/PreMailer.Net#368]
This code is perfectly valid CSS:

```CSS
 .emailsender {
    font-size: medium;
    font-size: max(16px, 1rem);
    -webkit-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    text-size-adjust: 100%; width: 100%;
}
```

but because there are two of the same properties (font-size), Premailer will only take the second one and ignore the first one.
